//riempe il contenuto dell' articolo con le biografie di Donald Trump, o di Kim Jong Un se si clicca sul loro nome nella navbar

function trumpBio(){
  var numP =0 //indica il numero del paragrafo
  document.createElement('h2');
  document.getElementById("history").appendChild(document.getElementsByTagName('h2')[0])
  document.getElementsByTagName('h2')[0].innerHTML='Chi é Donald Trump?';
    document.getElementById('p2').innerHTML='Una domanda che tutti ci siamo posti e che in vista dell’insediamento del Presidente torna a essere un quesito per molti. Soprattutto dopo le ultime dichiarazioni sul patrimonio del presidente e sulla sua vita privata.Nessuno poteva credere che Donald Trump sarebbe riuscito in questa impresa e i sondaggi lo davano piuttosto in svantaggio sulla sua avversaria. Trump ha però trionfato nei grandi stati americani, diventando così il nuovo presidente degli Stati Uniti.';
      document.getElementsByTagName('h3')[n].innerHTML='Vita pubblica';
  document.getElementById('p3').innerHTML="Donald Trump non può dirsi di certo un uomo che è venuto dal nulla, dal momento che già il padre è stato un ricco imprenditore americano. Padre e figlio hanno però puntato su due punti differenti dello stesso settore: Donald ha costruito immobili di lusso, il padre ha invece sempre puntano sulla costruzione di abitazioni in zone più popolari.Donald Trump si laurea in Economia e Finanza presso una delle università più prestigiose, alla Wharton School of Business.  Dopo aver concluso gli studi inizia a investire nel mondo immobiliare con l’azienda di famiglia: la Elizabeth Trump and Son.  L’azienda di famiglia si occupava di affittare case e appartamenti a Brooklyn, Queens e Staten Island. Un ambito ben diverso da quello che invece sarà il punto di forza dell’azienda di Donald Trump. Mentre Donald Trump era ancora impegnato con gli studi il padre decise di coinvolgerlo in uno dei suoi progetti: Swifton Village a Cincinnati."
  +"  Un complesso residenziale in Ohio, dove gli appartamenti sfitti erano oltre 1200 e il progetto sembrava essere in un momento di forte perdita.  Il programma ideato dal giovane Trump riuscì a dare grandi risultati, tanto che il complesso venne poi rivenduto per ben 6,7 miliardi di dollari. I primi successi Trump li ottiene nell’azienda di famiglia, che però ben presto comincia a stargli stretta, i suoi progetti sono di più ampio respiro.  Nel 1971 decide quindi di staccarsi dal padre e di cominciare ad investire nella zona più ricca di New York: Manhattan.  Il suo fu un vero e proprio successo, dal momento che riuscì ad essere coinvolto nei più grandi progetti della zona. Un esempio valga per tutti: la trasformazione dell’ormai fallito Commodore Hotel nel Grand Hyatt Hotel.  Un progetto grazie al quale riuscì ad avere ben 40 anni di detrazioni fiscali dal fisco di New York, per aver riportato in auge un edificio ormai sull’orlo della demolizione.";
  document.getElementsByTagName('h4')[0].innerHTML="Imprenditore,wrestler e attore";
  document.getElementById('p4').innerHTML="La vita di Donald Trump non si esaurisce con le sole esperienze imprenditoriali, ma quella del candidato repubblicano è una vita a tutto tondo. Trump è un grande appassionato di wrestling e la sua amicizia con il proprietario della World Wrestling Entertainment ha portato ad ospitare alcune edizioni del WrestleMania nel suo Trump Plaza."+"Trump stesso ha inoltre partecipato, in veste di ospite, ad alcuni show organizzati negli anni. Nel 2013 il nome di Donald Trump è stato inoltre inserito nella WWE Hall of Fame. Un riconoscimento per l’amore che negli anni ha dimostrato a questo sport."+"Donald Trump è conosciuto anche per le sue numerose apparizioni in show e film prodotti in America. Molti sono infatti i film in cui negli anni è comparso e gli show televisivi che lo hanno reso celebre non solo come imprenditore.";
  document.getElementById('p4').innerHTML=document.getElementById('p4').innerHTML+"Nel 1998 appare nel ruolo di se stesso per il film di Woody Allen, Celebrity, ma il pubblico americano lo conosce per il suo programma del 2004. In quest’anno infatti Trump appare sul piccolo con lo show The Apprentice, un programma in cui i vari aspiranti devono riuscire a colpire il ricco imprenditore per diventarne gli stagisti."+"Il programma, dopo le dichiarazioni contro gli immigrati effettuate da Trump, andò però in onda senza l’imprenditore, di cui il grande pubblico ricorda la frase: “You’re fired!” (sei licenziato).Anche in questa occasione Trump non è di certo passato inosservato e ha deciso di mettere bene in chiaro le sue idee."
  document.getElementsByTagName('h5')[0].innerHTML="Curiosità";
  document.getElementById('p5').innerHTML="Abbiamo fino a questo momento visto la vita di Trump e le sue passioni, adesso scopriamo qualcosa che non tutti sanno. Le curiosità su Donald Trump sono infatti molto interessanti, dal momento che ci dicono molto sul candidato alla Casa Bianca."+"Non tutti sanno che Trump è uno dei maggiori sostenitori dell’innocenza di Amanda Knox. Di certo le idee estreme del candidato repubblicano anche in questo caso non potevano essere pacate.Su Twitter ha anche affermato di aver aiutato la giovane e la famiglia nel ricongiungimento."+"Altra curiosità è il suo amore per le cravatte Marinella, una passione condivisa con molti personaggi importanti (come ad esempio Silvio Berlusconi). La passione di Trump è stata però così forte da provare anche ad avere un punto vendita nella sua Trump Tower.";
    document.getElementById('p5').innerHTML=  document.getElementById('p5').innerHTML+"L’investimento di Trump è però sfumato, dal momento che il proprietario del brand Marinella ha rifiutato l’offerta."+"Trump è inoltre conosciuto per le sue storie d'amore e soprattutto per le sue frasi di apprezzamento delle donne. Melania Trump, la sua attuale moglie, non è però l’unica con cui Donald aveva deciso di condividere il resto della sua vita.";
}




function kimBio(){
  document.getElementsByTagName('h2')[0].innerHTML='Chi é Kim Jong Un?';
  document.getElementById('p2').innerHTML="In molti lo definiscono un pazzo imprevedibile, un giovane lunatico con un Paese intero a disposizione con cui 'giocare' e un arsenale atomico per spaventare il mondo. Per anni si è sottovalutato Kim Jong-un, leader che oggi con i suoi esperimenti atomici sfida gli Stati Uniti di Donald Trump, preoccupa i Paesi della regione e irrita anche l'alleato cinese.";
  document.getElementsByTagName('h3')[0].innerHTML='Al potere a 27 anni';
  document.getElementById('p3').innerHTML="A tratteggiare un lungo profilo è il New York Times, che ripercorre le tappe salienti della vita del dittatore di Pyongyang. Il padre, Kim Jong-il, ha avuto tre mogli e almeno sei figli: fin da giovanissimo Jong-un è il prediletto, scavalca i fratelli e a 27 anni, alla morte del padre, conquista il potere, senza avere nessuna esperienza, come sottolineano alcuni analisti che ne predicono presto la fine. Invece lui resiste, e dopo sei anni è ancora alla guida del Paese.";
  document.getElementsByTagName('h4')[0].innerHTML="Ha studiato (forse) in Svizzera";
  document.getElementById('p4').innerHTML="Si ritiene che abbia studiato in scuole pubbliche svizzere, facendosi passare per il figlio di un diplomatico nord-coreano, e che questo periodo in Europa abbia lasciato un segno. Una volta rientrato in patria, ha frequentato l'università militare, avviandosi a prendere la leadership delle gerarchia militare."+"Non è mai uscito dalla Corea del Nord per visite di Stato, pochissimi stranieri hanno potuto varcare i confini del Paese e l'hanno incontrato, tra questi Dennis Rodman, famoso giocatore di basket americano, e uno chef di sushi giapponese, insieme ai vice presidenti di Cina e Cuba. ";
  document.getElementsByTagName('h5')[0].innerHTML='Ha fatto uccidere 140 funzionari';
  document.getElementById('p5').innerHTML="Si ritiene che tra le molte esecuzioni che abbia ordinato – è stato calcolato circa 140 alti funzionari da quando è salito al potere - c’è anche quella dello zio, Jang Song-thaek, per anni suo mentore e si riteneva reggente nell’ombra, accusato di tramare per detronizzarlo, e del fratellastro Kim Jong-nam, avvelenato all'aeroporto di Kuala Lumpur nel febbraio scorso. “Si è mosso velocemente e spietatamente. Penso che la maggior parte della gente non si aspettasse che un uomo cosi giovane fosse così efficiente nel gestire una dittatura”, ha commentato Daniel A. Pinkston, professore di relazioni internazionali alla Troy University.";
  document.getElementsByTagName('h6')[0].innerHTML='Un leader popolare';
  document.getElementById('p6').innerHTML="D'altra parte, sembra che abbia riconquistato una certa popolarità, dopo il regime del padre contraddistinto da una grave carestia, e abbia allentato il controllo dello stato sull'economia, dando una spinta per una certa crescita, promuovendo un forte sviluppo edilizio nella capitale e un maggiore accesso a cibo e beni. Ma fuori da Pyongyang la situazione è ben diversa e il peso delle sanzioni internazionali si fa sentire.";


}
